version: '3.8'

services:
  # Servicio PHP/Apache
  app:
    build: .
    container_name: gastropos-app
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_NAME=abastospos
      - DB_USER=root
      - DB_PASSWORD=
      - APP_URL=http://192.168.1.5:8080/Sistema de venta
    ports:
      - "0.0.0.0:8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - gastropos-network

networks:
  gastropos-network:
    driver: bridge
